version: '3.8'
services:
  property-manager:
    container_name: prop-manager
    build: .
    volumes: 
      - postgraphile:/postgraphile:ro
    restart: always
    depends_on:
      - postgraphile
    env_file:
      - .env
    environment:
      MIKRO_ORM_HOST: db
    ports:
      - "${PORT}:${PORT}"
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${MIKRO_ORM_USER}"
      POSTGRES_PASSWORD: "${MIKRO_ORM_PASSWORD}"
      POSTGRES_DB: "${MIKRO_ORM_DB_NAME}"
    ports:
      - "${MIKRO_ORM_PORT}:${MIKRO_ORM_PORT}"
  postgraphile:
    container_name: postgraphile
    image: graphile/postgraphile
    depends_on:
      - db
    restart: always
    ports: 
      - "${POSTGRAPHILE_PORT}:5000"
    command: [
      "--connection", "postgres://${MIKRO_ORM_USER}:${MIKRO_ORM_PASSWORD}@db:${MIKRO_ORM_PORT}/${MIKRO_ORM_DB_NAME}", 
      "--schema", "public", 
    ]
    volumes:
      - postgraphile:/postgraphile
volumes:
  postgraphile: